config/routes.rb
Rails.application.routes.draw do

  resources :restaurantes do 
    resources :tables
  end
  
  root 'restaurantes#index'
  get 'pages/dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
  has_many :tables, dependent: :destroy

  # Presence validation to ensure that name or other attributes neeeded to be mandatory is not empty
  validates :name, presence: true

  # Uniqueness validation to ensure that name or other attributes neeeded to be unique is/are not repeated
  validates :name, uniqueness: true
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :restaurante

  # Presence validation to ensure that number is not empty
  validates :number, presence: true

  # Numericality validation to ensure that number is an integer
  validates :number, numericality: { only_integer: true }

  # Uniqueness validation to ensure that number is unique
  validates :number, uniqueness: true

  # Greater than validation to ensure that number is greater than 0
  validates :number, numericality: { greater_than: 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
  end
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: %i[ show edit update destroy ]

  # GET /restaurantes or /restaurantes.json
  def index
    @restaurantes = Restaurante.all
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1 or /restaurantes/1.json
  def show
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes or /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to restaurantes_url(@restaurantes), notice: "Restaurante was successfully created." }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1 or /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to restaurante_url(@restaurante), notice: "Restaurante was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1 or /restaurantes/1.json
  def destroy
    @restaurante.destroy!

    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: "Restaurante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurante_params
      params.require(:restaurante).permit(:name)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_restaurante
  before_action :set_table, only: %i[ show edit update destroy ]
 
  
  # GET /tables or /tables.json
  def index
    @tables = @restaurante.tables
    @restaurante = Restaurante.find(params[:restaurante_id]) # Added
    @table = @restaurante.tables.build # Added
  end

  # GET /tables/1 or /tables/1.json
  def show
    @restaurante = @table.restaurante
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /tables/new
  def new
    @table = @restaurante.tables.build
  end

  # GET /tables/1/edit
  def edit
    @is_edit = params[:edit] == 'true'
    @table = @restaurante.tables.find(params[:id])
  end

  # POST /tables or /tables.json
  def create
   @table = @restaurante.tables.build(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to restaurante_tables_url(@restaurante, @table), notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @table = Table.find(params[:id])
    if @table.update(table_params)
      redirect_to restaurante_tables_url(@table.restaurante), notice: 'Table was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy!
    redirect_to restaurante_tables_url(@restaurante), notice: 'Table was successfully destroyed.'
    #respond_to do |format|
    #  format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = @restaurante.tables.find(params[:id])
    end

    def set_restaurante
      @restaurante = Restaurante.find(params[:restaurante_id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:number, :restaurante_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posters</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Pages#dashboard</h1>
<p>Find me in app/views/pages/dashboard.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<%= link_to "Posts", posts_path %>

app/views/restaurantes/_form.html.erb
<%= form_with(model: restaurante) do |form| %>
  <% if restaurante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
        <% restaurante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurantes/_restaurante.html.erb
<div id="<%= dom_id restaurante %>">
  <p>
    <strong>Name:</strong>
    <%= restaurante.name %>
  </p>

</div>

app/views/restaurantes/edit.html.erb
<h1>Editing restaurante</h1>

<%= render "form", restaurante: @restaurante %>

<br>

<div>
  <%= link_to "Show this restaurante", @restaurante %> |
  <%= link_to "Back to restaurantes", restaurantes_path %>
</div>

app/views/restaurantes/index.html.erb
<div data-controller='restaurantes' class='mb-5'>
  <div data-restaurantes-target='newForm' class='mt-5'>
    <h3>New Restaurante</h3>
    <%= form_with model: @restaurante, data: { action: 'restaurantes#submitForm' } do |form| %>
      <% if @restaurante.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>
          <ul>
            <% @restaurante.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>
      <div>
        <%= form.submit  %>
      </div>    
    <div>   
      <%= link_to "Cancel", restaurantes_path%>
    </div>
    <% end %>
  </div>
  <div class='mt-5'> 
    <a href="" data-action='click->restaurantes#openform' data-restaurantes-target='newLink'>New Restaurante</a>
  </div>  
</div>

<h1>Restaurantes</h1>
<div id="restaurantes">
  <% @restaurantes.each do |restaurante| %>
    <%= render restaurante %>
    <p>
      <%= link_to "Show this restaurante", restaurante %>
    </p>
  <% end %>
</div>

app/views/restaurantes/new.html.erb
<h1>New restaurante</h1>

<%= render "form", restaurante: @restaurante %>

<br>

<div>
  <%= link_to "Back to restaurantes", restaurantes_path %>
</div>

app/views/restaurantes/oldindex.html.erb
<p style="color: green"><%= notice %></p>
<div id='form' data-controller='restaurante-form' data-target='newForm'>
  <h3>New Restaurante</h3>
  <%= form_with(model: @restaurante) do |form| %>
    <% if @restaurante.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>
        <ul>
          <% @restaurante.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.submit  %>
    </div>
  <% end %>
  <div data-controller='new-link' data-new-link-restaurante-form-outlet='#form'>
    <%= link_to "New restaurante", new_restaurante_path, "data-action": "new_link#newForm" %>
  </div>
</div>


</div>
<h1>Restaurantes</h1>
<div id="restaurantes">
  <% @restaurantes.each do |restaurante| %>
    <%= render restaurante %>
    <p>
      <%= link_to "Show this restaurante", restaurante %>
    </p>
    <p>
      <%= link_to "Tables", restaurante_tables_path(restaurante) %>
    </p>
  <% end %>
</div>


<p style="color: green"><%= notice %></p>
<div id='form' data-controller='restaurante-form'>
  <h3>New Restaurante</h3>
  <%= form_with(model: @restaurante) do |form| %>
    <% if @restaurante.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>
        <ul>
          <% @restaurante.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.submit  %>
    </div>
  <% end %>
  <div data-controller='new-link' data-new-link-restaurante-form-outlet='#form'>
    <%= link_to "New restaurante", new_restaurante_path, "data-action": "new_link#showForm" %>
  </div>
</div>

With the code above I am trying to show/hide the form for creating a new restaurante. 
The form is hidden by default and should be shown when the user clicks on the "New restaurante" link. 
The form is shown when the user clicks on the link, but when the user clicks on the link again, the form is not hidden. 
I am using StimulusJS to show/hide the form.

# new_link_controller.js
```javascript
```

app/views/restaurantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurante %>

<div>
    <p>
      <%= link_to "Tables", restaurante_tables_path(@restaurante) %>
    </p>
  
  <%= link_to "Back to restaurantes", restaurantes_path %> | <%= link_to "Edit this restaurante", edit_restaurante_path(@restaurante) %> 
  <br/>
  <br/>
  <%= button_to "Destroy this restaurante", @restaurante, method: :delete %>
</div>

app/views/tables/_form.html.erb
<%= form_with(model: [@restaurante, @table]) do |form| %>
  <% if @table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% @table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/_table.html.erb
<div id="<%= dom_id table %>">
  <p>
    <strong>Number:</strong>
    <%= table.number %>
  </p>
    <p>
    <strong>Restaurante:</strong>
    <%= table.restaurante.name %>
  </p>
</div>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Show this table", restaurante_table_path(@table.restaurante, @table) %> |
  <%= link_to "Back to tables", restaurante_tables_path(@table.restaurante) %>
</div>

app/views/tables/index.html.erb
<p style="color: green"><%= notice %></p>
Back to <%= link_to "Restaurante", restaurante_path(@restaurante) %>
<div class='mt-3 mb-5'>
  Restaurante: <strong><%= @restaurante.name %></strong>
</div>
<div data-controller='tables' class='mb-5'>
  <%= form_with model: [@restaurante, @table], data: { action: "submit->tables#submit", tables_target: 'tableForm' } do |form| %>
    <% if @table.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>
        <ul>
          <% @table.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :number, style: "display: block" %>
      <%= form.text_field :number, data: { tables_target: 'number' } %>
    </div>
    <div class='mt-2'>
       <%= form.submit "Create Table", class: 'btn btn-login mt-3 mb-5', data: { tables_target: 'submitButton' } %>
    </div>
    <div>
      <%= link_to "Cancel", restaurante_tables_path(@restaurante)%>
    </div>
  <% end %>
  <div class='mt-5'data-tables-target='newLink'>
    <a href="" data-action='click->tables#opentableform'>New Table</a>
  </div>
  <div data-tables-target='tableList' >
    <h1 class='mt-4'>Tables</h1>
    <% @restaurante.tables.each do |table| %>
      <% if table && table.persisted? %>
        <%= render table %>
        <div class='mt-1 mb-5'>
          <a href="" data-action='click->tables#showTable' data-table-id="<%= table.id %>" data-restaurante-id="<%= @restaurante.id %>">Show</a> | 
          <%= link_to 'Edit Table', '#', data: { table_id: table.id, restaurante_id: table.restaurante_id,  action: 'click->tables#editTable', edit: true } %> | 
          <%= link_to "Delete", restaurante_table_path(table.restaurante, table.id), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div data-tables-target='table'>
    <div class=mb-5>
      <%= link_to "Back to Tables", restaurante_tables_path(@restaurante)%>
    </div>
    <h3>Table</h3>
    <div>
      <div>
        <p>
          <strong>Number:</strong>
          <span class="table-number"><%= @table.number %></span>
        </p>
        <p>
          <strong>Restaurante:</strong>
          <span class="table-restaurant"><%= @table.restaurante.name %></span>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%#= link_to "Back to tables", tables_path %>
</div>

app/views/tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table %>

<div>
  <%= link_to "Edit this table", edit_restaurante_table_path(@restaurante, @table) %> |
  <%= link_to "Back to tables", restaurante_tables_path(@restaurante) %>
</div>
<div class='mt-4'> 
  <%= button_to "Destroy this table",  restaurante_table_path(@restaurante, @table), method: :delete %>
</div>